import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Script from 'next/script';
import Header from './component/header/Header';
import Footer from './component/footer/Footer';
import { CartProvider } from './component/cart-context/CartContext';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DemoCart',
  description: 'Generated by Silby Shahanas',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <html lang="en">
      <head>
{/* <!-- Bootstrap Icons --> */}
     <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
      rel="stylesheet"
    /></head>
      <body className={inter.className}>
        <Header/>
        <div className="main-content">
        <CartProvider>
  {children}
        </CartProvider>     
        </div>
        <Footer/>
        
 {/* for carousel  */}
        <Script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
  strategy="afterInteractive"
/>

        </body>
    </html>
  )
}
